2025-02-25 18:06:49,566 INFO    MainThread:507782 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 18:06:49,567 INFO    MainThread:507782 [wandb_setup.py:_flush():67] Configure stats pid to 507782
2025-02-25 18:06:49,567 INFO    MainThread:507782 [wandb_setup.py:_flush():67] Loading settings from /home/minkyu/.config/wandb/settings
2025-02-25 18:06:49,567 INFO    MainThread:507782 [wandb_setup.py:_flush():67] Loading settings from /home/minkyu/gfn-diffusion/wandb/settings
2025-02-25 18:06:49,567 INFO    MainThread:507782 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 18:06:49,567 INFO    MainThread:507782 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/minkyu/gfn-diffusion/wandb/run-20250225_180649-ue0dpbsu/logs/debug.log
2025-02-25 18:06:49,568 INFO    MainThread:507782 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/minkyu/gfn-diffusion/wandb/run-20250225_180649-ue0dpbsu/logs/debug-internal.log
2025-02-25 18:06:49,568 INFO    MainThread:507782 [wandb_init.py:init():761] calling init triggers
2025-02-25 18:06:49,568 INFO    MainThread:507782 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'save_buffer_path': 'buffer_data.pt', 'load_buffer_path': None, 'lr_policy': 0.001, 'lr_flow': 0.1, 'lr_back': 0.001, 'hidden_dim': 64, 's_emb_dim': 64, 't_emb_dim': 64, 'harmonics_dim': 64, 'batch_size': 300, 'epochs': 200, 'buffer_size': 600000, 'T': 100, 'subtb_lambda': 2, 't_scale': 1.0, 'log_var_range': 4.0, 'energy': 'many_well', 'mode_fwd': 'tb', 'mode_bwd': 'tb', 'both_ways': True, 'local_search': False, 'max_iter_ls': 200, 'burn_in': 100, 'ls_cycle': 100, 'ld_step': 0.001, 'ld_schedule': False, 'target_acceptance_rate': 0.574, 'beta': 1.0, 'rank_weight': 0.01, 'prioritized': 'rank', 'bwd': False, 'exploratory': False, 'sampling': 'buffer', 'langevin': False, 'langevin_scaling_per_dimension': False, 'conditional_flow_model': False, 'learn_pb': False, 'pb_scale_range': 0.1, 'learned_variance': False, 'partial_energy': False, 'exploration_factor': 0.1, 'exploration_wd': False, 'clipping': True, 'lgv_clip': 100.0, 'gfn_clip': 10000.0, 'zero_init': True, 'pis_architectures': True, 'lgv_layers': 3, 'joint_layers': 2, 'seed': 12345, 'weight_decay': 1e-07, 'use_weight_decay': False, 'eval': False, 'Experiment': '{args.energy}', '_wandb': {}}
2025-02-25 18:06:49,568 INFO    MainThread:507782 [wandb_init.py:init():784] starting backend
2025-02-25 18:06:49,568 INFO    MainThread:507782 [wandb_init.py:init():788] sending inform_init request
2025-02-25 18:06:49,572 INFO    MainThread:507782 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-25 18:06:49,573 INFO    MainThread:507782 [wandb_init.py:init():803] backend started and connected
2025-02-25 18:06:49,576 INFO    MainThread:507782 [wandb_init.py:init():896] updated telemetry
2025-02-25 18:06:49,585 INFO    MainThread:507782 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-25 18:06:49,944 INFO    MainThread:507782 [wandb_init.py:init():995] starting run threads in backend
2025-02-25 18:06:50,154 INFO    MainThread:507782 [wandb_run.py:_console_start():2377] atexit reg
2025-02-25 18:06:50,155 INFO    MainThread:507782 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-25 18:06:50,155 INFO    MainThread:507782 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-25 18:06:50,155 INFO    MainThread:507782 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-25 18:06:50,160 INFO    MainThread:507782 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-25 18:07:54,949 WARNING MsgRouterThr:507782 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/compuworks/anaconda3/envs/gfn_school/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/compuworks/anaconda3/envs/gfn_school/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/compuworks/anaconda3/envs/gfn_school/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/compuworks/anaconda3/envs/gfn_school/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/compuworks/anaconda3/envs/gfn_school/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-25 18:07:54,951 INFO    MsgRouterThr:507782 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
